#!/usr/bin/env python3
"""Move an archive's initialized data (.data.* input sections) to PSRAM.

ESP-IDF can place zero-initialized data in PSRAM (.ext_ram.bss, zeroed at
start-up) but not initialized data: the bootloader loads .data before PSRAM
exists. So every .data.* section of the archive is renamed into .ext_ram.bss
(its contents are dropped from the image, it lands in PSRAM, zeroed), a global
symbol is planted at its start, its initial bytes are captured, and a C file
is generated that copies them back at run time (mgs_data_init(), to be called
before anything touches the data). Members are extracted by position, since
archive member names are not unique.

usage: data_to_psram.py <objdump> <objcopy> <ar> <archive> <out.c>
Idempotent: with no .data.* sections left the archive and out.c are untouched.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

objdump, objcopy, ar, archive, out_c = sys.argv[1:6]
archive = os.path.abspath(archive)


def run(*args):
    return subprocess.run(args, check=True, capture_output=True, text=True).stdout


names = run(ar, "t", archive).split()
work = tempfile.mkdtemp(prefix="data2psram_")
members = []  # (unique file path) in archive order
seen = {}
for name in names:
    seen[name] = seen.get(name, 0) + 1
    k = seen[name]
    # ar xN extracts the k-th member of that name
    subprocess.run([ar, "xN", str(k), archive, name], check=True, cwd=work)
    uniq = os.path.join(work, f"{len(members):04d}_{name}")
    os.rename(os.path.join(work, name), uniq)
    members.append(uniq)

entries = []  # (symbol, size, bytes)
touched = False
for idx, path in enumerate(members):
    secs = []
    for line in run(objdump, "-h", path).splitlines():
        p = line.split()
        if len(p) > 3 and p[0].isdigit() and (p[1] == ".data" or p[1].startswith(".data.")):
            size = int(p[2], 16)
            if size:
                secs.append((p[1], size))
    if not secs:
        continue
    touched = True
    renames, symbols = [], []
    for n, (sec, size) in enumerate(secs):
        binf = os.path.join(work, f"{idx}_{n}.bin")
        subprocess.run([objcopy, "-O", "binary", "--only-section=" + sec, path, binf], check=True)
        with open(binf, "rb") as f:
            data = f.read()
        if len(data) != size:  # objcopy -O binary pads to the section's file span
            data = (data + bytes(size))[:size]
        suffix = sec[len(".data."):] if sec.startswith(".data.") else f"data{n}"
        suffix = re.sub(r"[^A-Za-z0-9_.]", "_", suffix)
        new = f".ext_ram.bss.di.{suffix}"
        sym = f"mgs_di_{idx}_{n}"
        renames += ["--rename-section", f"{sec}={new}"]
        symbols += ["--add-symbol", f"{sym}={new}:0,global,object"]
        entries.append((sym, size, data))
    subprocess.run([objcopy] + renames + [path], check=True)
    subprocess.run([objcopy] + symbols + [path], check=True)

if touched:
    rebuilt = archive + ".new"
    if os.path.exists(rebuilt):
        os.remove(rebuilt)
    subprocess.run([ar, "rcs", rebuilt] + members, check=True)
    os.replace(rebuilt, archive)
    with open(out_c, "w") as f:
        f.write("/* generated by data_to_psram.py: the initial values of the game's .data,\n"
                " * copied into the PSRAM-resident variables by mgs_data_init() */\n"
                "#include <string.h>\n")
        # weak references: a member the link would not otherwise pull in must
        # not be pulled in by its copy entry (that is how two archive members
        # that define the same symbol coexist); an unlinked one resolves to 0
        # and is skipped
        for sym, size, data in entries:
            f.write(f"extern unsigned char {sym}[] __attribute__((weak));\n")
            f.write(f"static const unsigned char {sym}_init[{size}] = {{"
                    + ",".join(str(b) for b in data) + "};\n")
        f.write("void mgs_data_init(void) {\n")
        for sym, size, _ in entries:
            f.write(f"  if ({sym}) memcpy({sym}, {sym}_init, {size});\n")
        f.write("}\n")
    total = sum(e[1] for e in entries)
    print(f"data_to_psram: moved {len(entries)} .data sections ({total} bytes) of "
          f"{os.path.basename(archive)} to PSRAM; init copy in {os.path.basename(out_c)}")
elif not os.path.exists(out_c):
    with open(out_c, "w") as f:
        f.write("void mgs_data_init(void) {}\n")
shutil.rmtree(work, ignore_errors=True)
