set(GAME_SOURCE_FILES_PSYQ
    ${PSYQ}/src/libcard/card.c
    ${PSYQ}/src/libcard/init.c
    ${PSYQ}/src/libgpu/sys.c
    ${PSYQ}/src/libgpu/ext.c
    ${PSYQ}/src/libgpu/font.c
    ${PSYQ}/src/libgpu/otag.c
    ${PSYQ}/src/libgpu/prim.c
    ${PSYQ}/src/libgpu/tmd.c
    ${PSYQ}/src/libgte/sincos.c
    ${PSYQ}/src/libgte/sqrtbl.c
    ${PSYQ}/src/libgte/geo_00.c
    ${PSYQ}/src/libgte/geo_01.c
    ${PSYQ}/src/libgte/ratan.c
    ${PSYQ}/src/libcd/iso9660.c
    ${PSYQ}/src/libcd/sys.c
    ${PSYQ}/src/libcd/toc.c
    ${PSYQ}/src/libspu/s_cb.c
    ${PSYQ}/src/libspu/s_crwa.c
    ${PSYQ}/src/libspu/s_dcb.c
    ${PSYQ}/src/libspu/s_gtm.c
    ${PSYQ}/src/libspu/s_gva.c
    ${PSYQ}/src/libspu/s_i.c
    ${PSYQ}/src/libspu/s_ih.c
    ${PSYQ}/src/libspu/s_ini.c
    ${PSYQ}/src/libspu/s_it.c
    ${PSYQ}/src/libspu/s_itc.c
    ${PSYQ}/src/libspu/s_m.c
    ${PSYQ}/src/libspu/s_m_f.c
    ${PSYQ}/src/libspu/s_m_init.c
    ${PSYQ}/src/libspu/s_m_int.c
    ${PSYQ}/src/libspu/s_m_m.c
    ${PSYQ}/src/libspu/s_m_util.c
    ${PSYQ}/src/libspu/s_m_wsa.c
    ${PSYQ}/src/libspu/s_q.c
    ${PSYQ}/src/libspu/s_r.c
    ${PSYQ}/src/libspu/s_rmp.c
    ${PSYQ}/src/libspu/s_sca.c
    ${PSYQ}/src/libspu/s_sic.c
    ${PSYQ}/src/libspu/s_sk.c
    ${PSYQ}/src/libspu/s_snv.c
    ${PSYQ}/src/libspu/s_sr.c
    ${PSYQ}/src/libspu/s_stm.c
    ${PSYQ}/src/libspu/s_stsa.c
    ${PSYQ}/src/libspu/s_w.c
    ${PSYQ}/src/libspu/s_wp.c
    ${PSYQ}/src/libspu/spu.c
    ${PSYQ}/src/libspu/sr_gaks.c
    ${PSYQ}/src/libsnd/cres.c
    ${PSYQ}/src/libsnd/decres.c
    ${PSYQ}/src/libsnd/pause.c
    ${PSYQ}/src/libsnd/play.c
    ${PSYQ}/src/libsnd/playmode.c
    ${PSYQ}/src/libsnd/replay.c
    ${PSYQ}/src/libsnd/sscall.c
    ${PSYQ}/src/libsnd/ssclose.c
    ${PSYQ}/src/libsnd/sscres.c
    ${PSYQ}/src/libsnd/ssend.c
    ${PSYQ}/src/libsnd/ssinit.c
    ${PSYQ}/src/libsnd/ssinit_c.c
    ${PSYQ}/src/libsnd/ssinit_h.c
    ${PSYQ}/src/libsnd/ssloop.c
    ${PSYQ}/src/libsnd/ssopenp.c
    ${PSYQ}/src/libsnd/ssplay.c
    ${PSYQ}/src/libsnd/ssquit.c
    ${PSYQ}/src/libsnd/sssattr.c
    ${PSYQ}/src/libsnd/sssmv.c
    ${PSYQ}/src/libsnd/ssstart.c
    ${PSYQ}/src/libsnd/ssstop.c
    ${PSYQ}/src/libsnd/sssv.c
    ${PSYQ}/src/libsnd/ssvol.c
    ${PSYQ}/src/libsnd/sstable.c
    ${PSYQ}/src/libsnd/sstick.c
    ${PSYQ}/src/libsnd/sstickcb.c
    ${PSYQ}/src/libsnd/ut_ako.c
    ${PSYQ}/src/libsnd/ut_autop.c
    ${PSYQ}/src/libsnd/ut_cadsr.c
    ${PSYQ}/src/libsnd/ut_key.c
    ${PSYQ}/src/libsnd/ut_keyv.c
    ${PSYQ}/src/libsnd/ut_rdel.c
    ${PSYQ}/src/libsnd/ut_rdep.c
    ${PSYQ}/src/libsnd/ut_rev.c
    ${PSYQ}/src/libsnd/ut_roff.c
    ${PSYQ}/src/libsnd/ut_ron.c
    ${PSYQ}/src/libsnd/ut_vvol.c
    ${PSYQ}/src/libsnd/vol.c
    ${PSYQ}/src/libsnd/vm_aloc2.c
    ${PSYQ}/src/libsnd/vm_autop.c
    ${PSYQ}/src/libsnd/vm_doff.c
    ${PSYQ}/src/libsnd/vm_f.c
    ${PSYQ}/src/libsnd/vm_g.c
    ${PSYQ}/src/libsnd/vm_init.c
    ${PSYQ}/src/libsnd/vm_n2p.c
    ${PSYQ}/src/libsnd/vm_noff.c
    ${PSYQ}/src/libsnd/vm_nowof.c
    ${PSYQ}/src/libsnd/vm_nowon.c
    ${PSYQ}/src/libsnd/vm_vsu.c
    ${PSYQ}/src/libsnd/vs_mono.c
    ${PSYQ}/src/libsnd/vs_srv.c
    ${PSYQ}/src/libsnd/vs_vab.c
    ${PSYQ}/src/libsnd/vs_vh.c
    ${PSYQ}/src/libsnd/vs_vtb.c
    ${PSYQ}/src/libsnd/vs_vtbp.c
    ${PSYQ}/src/libsnd/vs_vtc.c
)
